website/download.ejs, website/features.ejs
seems that I forgot some of the ') before... kudos to to my colleague, who made me aware of this :-)
=> some more ') and other typos

documentation/docs/user-guide-tour.md, documentation/website/versioned_docs/version-0.62.0-pre-asf/user-guide-tour.md, documentation/website/versioned_docs/version-0.65.0-pre-asf/user-guide-tour.md
This PR will fix the broken src for Connection Error image of pipeline editor.
[1] https://streampipes.apache.org/docs/docs/user-guide-tour/#pipeline-editor
=> Fix connection error image src link

documentation/docs/user-guide-installation.md
=> Fix installation steps in user documentation as per the latest release

documentation/docs/05_deploy-docker.md, documentation/docs/06_extend-tutorial-data-sinks.md, documentation/docs/06_extend-tutorial-data-sources.md, documentation/website/siteConfig.js
Some of the links on the webpage are broken.
I've copied a couple of examples from other sections that are working.
The Streampipes CLI link on this page
https://streampipes.apache.org/docs/docs/deploy-docker/
Fixes: https://issues.apache.org/jira/browse/STREAMPIPES-356
Hopeful fix for some of them.
=> [STREAMPIPES-356] Possible fix for a few of the links that are broken

documentation/website/versioned_docs/version-0.67.0/06_extend-tutorial-data-processors.md
Since version 0.66.0 the groupId of this archetype is org.apache.streampipes
Update example
=> Update groupId of flink processor archetype

website/team.ejs
=> Add new member: Zike Yang

documentation/website/pages/en/versions.js
Fix some broken links on the project's version overview
Fixes: https://issues.apache.org/jira/browse/STREAMPIPES-599
=> [STREAMPIPES-599] Fix broken links in version overview

documentation/website/pages/en/versions.js
* [STREAMPIPES-599] fix broken links on project's version overview
* [STREAMPIPES-599] Add link to issue tracker
* [STREAMPIPES-599] improve appearance
Co-authored-by: Philipp Zehnder <zehnder@fzi.de>
=> [STREAMPIPES-599] Fix broken links in version overview (#30)

documentation/docs/06_extend-sdk-functions.md, documentation/website/i18n/en.json, documentation/website/pages/en/versions.js, documentation/website/sidebars.json
Add basic documentation on how to use StreamPipes functions.
Fixes: <Jira issue link>
=> docs: Add documentation for functions (apache/streampipes#751)

.github/PULL_REQUEST_TEMPLATE.md, documentation/docs/09_contribute.md, documentation/docs/09_get-help.md, documentation/website/pages/en/versions.js, website/getinvolved.ejs, website/partials/_nav.ejs
=> remove pointers to jira

documentation/docs/06_extend-cli.md, documentation/docs/06_extend-tutorial-data-processors.md, documentation/docs/06_extend-tutorial-data-sinks.md, documentation/docs/06_extend-tutorial-data-sources.md
Update the existing tutorials in the documentation
=> Update tutorials (apache/streampipes#769)

website/team.ejs
=> add new member Xin Wang

.github/dependabot.yaml, .gitignore, documentation/website/package-lock.json, package-lock.json, package.json
Configure dependabot properly for streampipes-website
=> Chore/configure dependabot for streampipes-website

documentation/website/versioned_docs/version-0.70.0/09_get-help.md
Replace Slack community link with link to Github Discussions
=> Remove Slack channel from community page

website/download.ejs
=> traget help link on download page to Github discussions

website/meetus.ejs, website/partials/_index-teaser.ejs
Add upcoming StreamPipes talks at FOSSGIS and buildingIot
=> chore: add information about upcoming events

website/meetus.ejs, website/partials/_index-teaser.ejs
=> chore: add pycon talk to events overview

website/meetus.ejs
=> add-ionos-event

.github/workflows/update-python-docs.yml
This PR uses the artifacts provided by the workflow introduced in https://github.com/apache/streampipes/pull/1263.
It downloads the python docs assets, adds them to the source and creates a PR that allows to easily update the docs.
=> chore(gh-actions): create workflow that updates python docs

website/meetus.ejs
=> chore: update events page

website-v2/src/components/download/DownloadBox.tsx
Fix link to PGP hash and sperate singature links visually on webpage.
=> Fix link to PGP hash and sperate singature links visually on webpage.

docs/pe/org.apache.streampipes.processors.transformation.jvm.round.md
Add documentation for numeric rounding element
=> add-rounding-doc

docs/05_deploy-choosing-the-right-flavor.md, docs/05_deploy-environment-variables.md, docs/05_deploy-kubernetes.md, docs/06_extend-customize-ui.md, docs/07_technicals-messaging.md, docs/07_technicals-runtime-wrappers.md, website-v2/sidebars.json, website-v2/versioned_sidebars/version-0.92.0-sidebars.json
Extend and update several docs pages:
* Add a new page on UI customization
* Add a new page on available environment variables
* Add existing k8s configuration options to the Kubernetes documentation
* Extend messaging configuration section
* Add basic runtime wrapper section
* Disable User Guidance section for now since there was no content
=> Add documentation pages for env variables and UI customization

docs/pe/org.apache.streampipes.connect.iiot.protocol.stream.httpserver.md
Inspired by #apache/streampipes/discussions/2299
Extend the adapter documentation.
PR introduces (a) breaking change(s): no
PR introduces (a) deprecation(s): no
=> Update HTTP Server adapter documentation

README.md
Fix GitHub Actions badge.
- Before the amend:
[![Github Actions](https://img.shields.io/github/workflow/status/apache/streampipes-website/Build%20and%20Deploy)](https://github.com/apache/streampipes-website/actions/)
- After the amend:
[![Github Actions](https://img.shields.io/github/actions/workflow/status/apache/streampipes-website/deploy-website.yml?label=Build%20and%20Deploy)](https://github.com/apache/streampipes-website/actions/)
=> fix: correction GitHub Actions badge

docs/05_deploy-security.md
Add a new section to the `Security´ page which explains how to configure third-party OAuth authentication.
=> Add section on OAuth configuration
